/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_mainWindow (void)
{
  GtkWidget *mainWindow;
  GtkWidget *table1;
  GtkWidget *menubar1;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *open1;
  GtkWidget *separator1;
  GtkWidget *quit1;
  GtkWidget *game_state1;
  GtkWidget *game_state1_menu;
  GtkAccelGroup *game_state1_menu_accels;
  GtkWidget *save1;
  GtkWidget *load1;
  GtkWidget *options1;
  GtkWidget *options1_menu;
  GtkAccelGroup *options1_menu_accels;
  GtkWidget *general_settings_1;
  GtkWidget *input_setting_1;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *hugo_manual1;
  GtkWidget *separator2;
  GtkWidget *about_1;
  GtkWidget *statusbar1;
  GtkWidget *hbox1;
  GtkWidget *button1;
  GtkWidget *hbox2;
  GtkWidget *pixmap2;
  GtkWidget *label1;
  GtkWidget *button2;
  GtkWidget *hbox3;
  GtkWidget *pixmap3;
  GtkWidget *label2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  mainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (mainWindow), "mainWindow", mainWindow);
  gtk_window_set_title (GTK_WINDOW (mainWindow), "Hu-Go! - PC Engine Emulator");
  gtk_window_set_position (GTK_WINDOW (mainWindow), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (mainWindow), TRUE, TRUE, TRUE);

  table1 = gtk_table_new (3, 1, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (mainWindow), table1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_table_attach (GTK_TABLE (table1), menubar1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  file1 = gtk_menu_item_new_with_label ("File");
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (menubar1), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  open1 = gtk_menu_item_new_with_label ("Open...");
  gtk_widget_ref (open1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "open1", open1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (file1_menu), open1);
  gtk_widget_add_accelerator (open1, "activate", accel_group,
                              GDK_o, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator1 = gtk_menu_item_new ();
  gtk_widget_ref (separator1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "separator1", separator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (file1_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  quit1 = gtk_menu_item_new_with_label ("Quit");
  gtk_widget_ref (quit1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "quit1", quit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (file1_menu), quit1);
  gtk_widget_add_accelerator (quit1, "activate", accel_group,
                              GDK_q, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  game_state1 = gtk_menu_item_new_with_label ("Game state");
  gtk_widget_ref (game_state1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "game_state1", game_state1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (game_state1);
  gtk_container_add (GTK_CONTAINER (menubar1), game_state1);

  game_state1_menu = gtk_menu_new ();
  gtk_widget_ref (game_state1_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "game_state1_menu", game_state1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (game_state1), game_state1_menu);
  game_state1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (game_state1_menu));

  save1 = gtk_menu_item_new_with_label ("Save");
  gtk_widget_ref (save1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "save1", save1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (game_state1_menu), save1);

  load1 = gtk_menu_item_new_with_label ("Load");
  gtk_widget_ref (load1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "load1", load1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (load1);
  gtk_container_add (GTK_CONTAINER (game_state1_menu), load1);

  options1 = gtk_menu_item_new_with_label ("Options");
  gtk_widget_ref (options1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "options1", options1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (options1);
  gtk_container_add (GTK_CONTAINER (menubar1), options1);

  options1_menu = gtk_menu_new ();
  gtk_widget_ref (options1_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "options1_menu", options1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (options1), options1_menu);
  options1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (options1_menu));

  general_settings_1 = gtk_menu_item_new_with_label ("General settings ...");
  gtk_widget_ref (general_settings_1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "general_settings_1", general_settings_1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (general_settings_1);
  gtk_container_add (GTK_CONTAINER (options1_menu), general_settings_1);

  input_setting_1 = gtk_menu_item_new_with_label ("Input settings ...");
  gtk_widget_ref (input_setting_1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "input_setting_1", input_setting_1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (input_setting_1);
  gtk_container_add (GTK_CONTAINER (options1_menu), input_setting_1);

  help1 = gtk_menu_item_new_with_label ("Help");
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menubar1), help1);

  help1_menu = gtk_menu_new ();
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  hugo_manual1 = gtk_menu_item_new_with_label ("Hu-go! manual");
  gtk_widget_ref (hugo_manual1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "hugo_manual1", hugo_manual1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hugo_manual1);
  gtk_container_add (GTK_CONTAINER (help1_menu), hugo_manual1);

  separator2 = gtk_menu_item_new ();
  gtk_widget_ref (separator2);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "separator2", separator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (help1_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  about_1 = gtk_menu_item_new_with_label ("About ...");
  gtk_widget_ref (about_1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "about_1", about_1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about_1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about_1);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "statusbar1", statusbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_table_attach (GTK_TABLE (table1), statusbar1, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_table_attach (GTK_TABLE (table1), hbox1, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  button1 = gtk_button_new ();
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (hbox1), button1, FALSE, FALSE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (button1), hbox2);

  pixmap2 = create_pixmap (mainWindow, "pce.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox2), pixmap2, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (pixmap2), 2, 2);

  label1 = gtk_label_new ("Open Rom");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox2), label1, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_box_pack_start (GTK_BOX (hbox1), button2, FALSE, FALSE, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (button2), hbox3);

  pixmap3 = create_pixmap (mainWindow, "i-cdrom.xpm");
  gtk_widget_ref (pixmap3);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "pixmap3", pixmap3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap3);
  gtk_box_pack_start (GTK_BOX (hbox3), pixmap3, TRUE, TRUE, 0);

  label2 = gtk_label_new ("Open Cd");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox3), label2, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (mainWindow), "destroy",
                      GTK_SIGNAL_FUNC (on_mainWindow_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (open1), "activate",
                      GTK_SIGNAL_FUNC (on_open1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (quit1), "activate",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save1), "activate",
                      GTK_SIGNAL_FUNC (on_save1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (load1), "activate",
                      GTK_SIGNAL_FUNC (on_load1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (general_settings_1), "activate",
                      GTK_SIGNAL_FUNC (on_general_settings_1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (input_setting_1), "activate",
                      GTK_SIGNAL_FUNC (on_input_setting_1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (hugo_manual1), "activate",
                      GTK_SIGNAL_FUNC (on_hugo_manual1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about_1), "activate",
                      GTK_SIGNAL_FUNC (on_about_1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_button1_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (on_button2_clicked),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (mainWindow), accel_group);

  return mainWindow;
}

GtkWidget*
create_fileselection1 (void)
{
  GtkWidget *fileselection1;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;

  fileselection1 = gtk_file_selection_new ("Select File");
  gtk_object_set_data (GTK_OBJECT (fileselection1), "fileselection1", fileselection1);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection1), 10);
  gtk_window_set_policy (GTK_WINDOW (fileselection1), TRUE, TRUE, FALSE);

  ok_button1 = GTK_FILE_SELECTION (fileselection1)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection1), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (fileselection1)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection1), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (fileselection1), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button1_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button1_clicked),
                      NULL);

  return fileselection1;
}

GtkWidget*
create_input_settings_window (void)
{
  GtkWidget *input_settings_window;
  GtkWidget *vbox1;
  GtkWidget *hbox4;
  GtkWidget *option_config_number;
  GtkWidget *option_config_number_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *button_use_current_config;
  GtkWidget *hbox6;
  GtkWidget *option_player_number;
  GtkWidget *option_player_number_menu;
  GtkWidget *button_configure_this_player;
  GtkWidget *hbox7;
  GtkWidget *option_device_type;
  GtkWidget *option_device_type_menu;
  GtkWidget *button_use_this_device;
  GtkWidget *hbox5;
  GtkWidget *table2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *button_grab_up;
  GtkWidget *button_grab_down;
  GtkWidget *button_grab_left;
  GtkWidget *button_grab_right;
  GtkWidget *button_grab_select;
  GtkWidget *button_grab_run;
  GtkWidget *button_grab_I;
  GtkWidget *button_grab_II;
  GtkWidget *button_grab_auto_I;
  GtkWidget *button_grab_auto_II;
  GtkWidget *label_up;
  GtkWidget *label_down;
  GtkWidget *label_left;
  GtkWidget *label_right;
  GtkWidget *label_select;
  GtkWidget *label_run;
  GtkWidget *label_i;
  GtkWidget *label_ii;
  GtkWidget *label_auto_i;
  GtkWidget *label_auto_ii;
  GtkWidget *alignment2;
  GtkWidget *button_close_input_settings_window;

  input_settings_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (input_settings_window), "input_settings_window", input_settings_window);
  gtk_window_set_title (GTK_WINDOW (input_settings_window), "Input settings");
  gtk_window_set_policy (GTK_WINDOW (input_settings_window), TRUE, TRUE, TRUE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (input_settings_window), vbox1);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox4, FALSE, TRUE, 0);

  option_config_number = gtk_option_menu_new ();
  gtk_widget_ref (option_config_number);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "option_config_number", option_config_number,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (option_config_number);
  gtk_box_pack_start (GTK_BOX (hbox4), option_config_number, FALSE, FALSE, 0);
  option_config_number_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 1");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 2");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 3");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 4");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 5");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 6");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 7");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 8");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 9");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 10");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 11");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 12");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 13");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 14");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 15");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Configuration 16");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_config_number_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (option_config_number), option_config_number_menu);

  button_use_current_config = gtk_button_new_with_label ("Use this config");
  gtk_widget_ref (button_use_current_config);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_use_current_config", button_use_current_config,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_use_current_config);
  gtk_box_pack_start (GTK_BOX (hbox4), button_use_current_config, FALSE, FALSE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox6, TRUE, TRUE, 0);

  option_player_number = gtk_option_menu_new ();
  gtk_widget_ref (option_player_number);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "option_player_number", option_player_number,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (option_player_number);
  gtk_box_pack_start (GTK_BOX (hbox6), option_player_number, FALSE, FALSE, 0);
  option_player_number_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label ("Player 1");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_player_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Player 2");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_player_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Player 3");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_player_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Player 4");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_player_number_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Player 5");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_player_number_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (option_player_number), option_player_number_menu);

  button_configure_this_player = gtk_button_new_with_label ("Configure this player");
  gtk_widget_ref (button_configure_this_player);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_configure_this_player", button_configure_this_player,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_configure_this_player);
  gtk_box_pack_start (GTK_BOX (hbox6), button_configure_this_player, FALSE, FALSE, 0);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox7);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "hbox7", hbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox7, TRUE, TRUE, 0);

  option_device_type = gtk_option_menu_new ();
  gtk_widget_ref (option_device_type);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "option_device_type", option_device_type,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (option_device_type);
  gtk_box_pack_start (GTK_BOX (hbox7), option_device_type, FALSE, FALSE, 0);
  option_device_type_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label ("None");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Keyboard 1");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Keyboard 2");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Keyboard 3");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Keyboard 4");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Keyboard 5");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Joypad 1");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Joypad 2");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Joypad 3");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Joypad 4");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Joypad 5");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Mouse 1");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Mouse 2");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Network");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label ("Synaptic link");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (option_device_type_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (option_device_type), option_device_type_menu);

  button_use_this_device = gtk_button_new_with_label ("Use this device");
  gtk_widget_ref (button_use_this_device);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_use_this_device", button_use_this_device,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_use_this_device);
  gtk_box_pack_start (GTK_BOX (hbox7), button_use_this_device, FALSE, FALSE, 0);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox5, TRUE, TRUE, 0);

  table2 = gtk_table_new (10, 3, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (hbox5), table2, TRUE, TRUE, 0);

  label3 = gtk_label_new ("UP : ");
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table2), label3, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label3), 1, 0.5);

  label4 = gtk_label_new ("DOWN : ");
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table2), label4, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label4), 1, 0.5);

  label5 = gtk_label_new ("LEFT : ");
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table2), label5, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 1, 0.5);

  label6 = gtk_label_new ("RIGHT : ");
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table2), label6, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 1, 0.5);

  label7 = gtk_label_new ("SELECT : ");
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table2), label7, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 1, 0.5);

  label8 = gtk_label_new ("RUN : ");
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table2), label8, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 1, 0.5);

  label9 = gtk_label_new ("I : ");
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table2), label9, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 1, 0.5);

  label10 = gtk_label_new ("II : ");
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table2), label10, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 1, 0.5);

  label11 = gtk_label_new ("TOGGLE AUTO I : ");
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table2), label11, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 1, 0.5);

  label12 = gtk_label_new ("TOGGLE AUTO II : ");
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table2), label12, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 1, 0.5);

  button_grab_up = gtk_button_new_with_label ("grab ...");
  gtk_widget_ref (button_grab_up);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_grab_up", button_grab_up,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_grab_up);
  gtk_table_attach (GTK_TABLE (table2), button_grab_up, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_grab_down = gtk_button_new_with_label ("grab ...");
  gtk_widget_ref (button_grab_down);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_grab_down", button_grab_down,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_grab_down);
  gtk_table_attach (GTK_TABLE (table2), button_grab_down, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_grab_left = gtk_button_new_with_label ("grab ...");
  gtk_widget_ref (button_grab_left);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_grab_left", button_grab_left,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_grab_left);
  gtk_table_attach (GTK_TABLE (table2), button_grab_left, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_grab_right = gtk_button_new_with_label ("grab ...");
  gtk_widget_ref (button_grab_right);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_grab_right", button_grab_right,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_grab_right);
  gtk_table_attach (GTK_TABLE (table2), button_grab_right, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_grab_select = gtk_button_new_with_label ("grab ...");
  gtk_widget_ref (button_grab_select);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_grab_select", button_grab_select,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_grab_select);
  gtk_table_attach (GTK_TABLE (table2), button_grab_select, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_grab_run = gtk_button_new_with_label ("grab ...");
  gtk_widget_ref (button_grab_run);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_grab_run", button_grab_run,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_grab_run);
  gtk_table_attach (GTK_TABLE (table2), button_grab_run, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_grab_I = gtk_button_new_with_label ("grab ...");
  gtk_widget_ref (button_grab_I);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_grab_I", button_grab_I,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_grab_I);
  gtk_table_attach (GTK_TABLE (table2), button_grab_I, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_grab_II = gtk_button_new_with_label ("grab ...");
  gtk_widget_ref (button_grab_II);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_grab_II", button_grab_II,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_grab_II);
  gtk_table_attach (GTK_TABLE (table2), button_grab_II, 2, 3, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_grab_auto_I = gtk_button_new_with_label ("grab ...");
  gtk_widget_ref (button_grab_auto_I);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_grab_auto_I", button_grab_auto_I,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_grab_auto_I);
  gtk_table_attach (GTK_TABLE (table2), button_grab_auto_I, 2, 3, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_grab_auto_II = gtk_button_new_with_label ("grab ...");
  gtk_widget_ref (button_grab_auto_II);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_grab_auto_II", button_grab_auto_II,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_grab_auto_II);
  gtk_table_attach (GTK_TABLE (table2), button_grab_auto_II, 2, 3, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label_up = gtk_label_new ("");
  gtk_widget_ref (label_up);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label_up", label_up,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_up);
  gtk_table_attach (GTK_TABLE (table2), label_up, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_up), 0, 0.5);

  label_down = gtk_label_new ("");
  gtk_widget_ref (label_down);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label_down", label_down,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_down);
  gtk_table_attach (GTK_TABLE (table2), label_down, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_down), 0, 0.5);

  label_left = gtk_label_new ("");
  gtk_widget_ref (label_left);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label_left", label_left,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_left);
  gtk_table_attach (GTK_TABLE (table2), label_left, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_left), 0, 0.5);

  label_right = gtk_label_new ("");
  gtk_widget_ref (label_right);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label_right", label_right,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_right);
  gtk_table_attach (GTK_TABLE (table2), label_right, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_right), 0, 0.5);

  label_select = gtk_label_new ("");
  gtk_widget_ref (label_select);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label_select", label_select,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_select);
  gtk_table_attach (GTK_TABLE (table2), label_select, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_select), 0, 0.5);

  label_run = gtk_label_new ("");
  gtk_widget_ref (label_run);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label_run", label_run,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_run);
  gtk_table_attach (GTK_TABLE (table2), label_run, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_run), 0, 0.5);

  label_i = gtk_label_new ("");
  gtk_widget_ref (label_i);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label_i", label_i,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_i);
  gtk_table_attach (GTK_TABLE (table2), label_i, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_i), 0, 0.5);

  label_ii = gtk_label_new ("");
  gtk_widget_ref (label_ii);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label_ii", label_ii,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_ii);
  gtk_table_attach (GTK_TABLE (table2), label_ii, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_ii), 0, 0.5);

  label_auto_i = gtk_label_new ("");
  gtk_widget_ref (label_auto_i);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label_auto_i", label_auto_i,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_auto_i);
  gtk_table_attach (GTK_TABLE (table2), label_auto_i, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_auto_i), 0, 0.5);

  label_auto_ii = gtk_label_new ("");
  gtk_widget_ref (label_auto_ii);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "label_auto_ii", label_auto_ii,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_auto_ii);
  gtk_table_attach (GTK_TABLE (table2), label_auto_ii, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_auto_ii), 0, 0.5);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0.0400005, 1);
  gtk_widget_ref (alignment2);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "alignment2", alignment2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (alignment2);
  gtk_box_pack_end (GTK_BOX (vbox1), alignment2, FALSE, FALSE, 2);

  button_close_input_settings_window = gtk_button_new_with_label ("Close");
  gtk_widget_ref (button_close_input_settings_window);
  gtk_object_set_data_full (GTK_OBJECT (input_settings_window), "button_close_input_settings_window", button_close_input_settings_window,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_close_input_settings_window);
  gtk_container_add (GTK_CONTAINER (alignment2), button_close_input_settings_window);

  gtk_signal_connect (GTK_OBJECT (button_use_current_config), "clicked",
                      GTK_SIGNAL_FUNC (on_button_use_current_config_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (option_player_number), "clicked",
                      GTK_SIGNAL_FUNC (on_option_device_number_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_configure_this_player), "clicked",
                      GTK_SIGNAL_FUNC (on_button_configure_this_player_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (option_device_type), "clicked",
                      GTK_SIGNAL_FUNC (on_option_device_type_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_use_this_device), "clicked",
                      GTK_SIGNAL_FUNC (on_button_use_this_device_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_grab_up), "clicked",
                      GTK_SIGNAL_FUNC (on_button_grab_clicked),
                      0);
  gtk_signal_connect (GTK_OBJECT (button_grab_down), "clicked",
                      GTK_SIGNAL_FUNC (on_button_grab_clicked),
                      1);
  gtk_signal_connect (GTK_OBJECT (button_grab_left), "clicked",
                      GTK_SIGNAL_FUNC (on_button_grab_clicked),
                      2);
  gtk_signal_connect (GTK_OBJECT (button_grab_right), "clicked",
                      GTK_SIGNAL_FUNC (on_button_grab_clicked),
                      3);
  gtk_signal_connect (GTK_OBJECT (button_grab_select), "clicked",
                      GTK_SIGNAL_FUNC (on_button_grab_clicked),
                      6);
  gtk_signal_connect (GTK_OBJECT (button_grab_run), "clicked",
                      GTK_SIGNAL_FUNC (on_button_grab_clicked),
                      7);
  gtk_signal_connect (GTK_OBJECT (button_grab_I), "clicked",
                      GTK_SIGNAL_FUNC (on_button_grab_clicked),
                      4);
  gtk_signal_connect (GTK_OBJECT (button_grab_II), "clicked",
                      GTK_SIGNAL_FUNC (on_button_grab_clicked),
                      5);
  gtk_signal_connect (GTK_OBJECT (button_grab_auto_I), "clicked",
                      GTK_SIGNAL_FUNC (on_button_grab_clicked),
                      8);
  gtk_signal_connect (GTK_OBJECT (button_grab_auto_II), "clicked",
                      GTK_SIGNAL_FUNC (on_button_grab_clicked),
                      9);
  gtk_signal_connect (GTK_OBJECT (button_close_input_settings_window), "clicked",
                      GTK_SIGNAL_FUNC (on_button_close_input_settings_window_clicked),
                      NULL);

  return input_settings_window;
}

GtkWidget*
create_general_settings_window (void)
{
  GtkWidget *general_settings_window;
  GtkWidget *vbox3;
  GtkWidget *notebook1;
  GtkWidget *table7;
  GtkWidget *checkbutton_start_fullscreen;
  GtkWidget *checkbutton_maintain_aspect;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *entry_fullscreen_width;
  GtkWidget *entry_fullscreen_height;
  GtkObject *spinbutton_window_size_adj;
  GtkWidget *spinbutton_window_size;
  GtkWidget *label27;
  GtkWidget *table3;
  GtkWidget *entry_cd_system_filename;
  GtkWidget *button_browse_cd_system;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *entry_rom_basedir;
  GtkWidget *button_browse_rom_dirname;
  GtkWidget *label_paths;
  GtkWidget *table4;
  GtkWidget *checkbutton_minimal_bios;
  GtkWidget *label21;
  GtkWidget *entry_cd_path;
  GtkWidget *button_browse_cd_path;
  GtkWidget *label_cd;
  GtkWidget *table5;
  GtkWidget *label22;
  GtkWidget *entry_output_frequency;
  GtkWidget *entry_buffer_size;
  GtkWidget *label23;
  GtkWidget *checkbutton_stereo_sound;
  GtkWidget *label_sound;
  GtkWidget *hbuttonbox1;
  GtkWidget *buttongeneral_config_close;
  GtkWidget *button_general_config_save;
  GtkWidget *button_general_config_cancel;

  general_settings_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (general_settings_window), "general_settings_window", general_settings_window);
  gtk_window_set_title (GTK_WINDOW (general_settings_window), "General settings");
  gtk_window_set_policy (GTK_WINDOW (general_settings_window), TRUE, TRUE, TRUE);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (general_settings_window), vbox3);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox3), notebook1, TRUE, TRUE, 0);

  table7 = gtk_table_new (4, 4, FALSE);
  gtk_widget_ref (table7);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "table7", table7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table7);
  gtk_container_add (GTK_CONTAINER (notebook1), table7);

  checkbutton_start_fullscreen = gtk_check_button_new_with_label ("Start games in fullscreen mode");
  gtk_widget_ref (checkbutton_start_fullscreen);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "checkbutton_start_fullscreen", checkbutton_start_fullscreen,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton_start_fullscreen);
  gtk_table_attach (GTK_TABLE (table7), checkbutton_start_fullscreen, 0, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton_maintain_aspect = gtk_check_button_new_with_label ("Maintain pce aspect ratio in fullscreen mode");
  gtk_widget_ref (checkbutton_maintain_aspect);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "checkbutton_maintain_aspect", checkbutton_maintain_aspect,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton_maintain_aspect);
  gtk_table_attach (GTK_TABLE (table7), checkbutton_maintain_aspect, 0, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label28 = gtk_label_new ("Window size : ");
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table7), label28, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label29 = gtk_label_new ("Fullscreen mode : ");
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table7), label29, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new ("x");
  gtk_widget_ref (label30);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label30", label30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table7), label30, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  entry_fullscreen_width = gtk_entry_new_with_max_length (4);
  gtk_widget_ref (entry_fullscreen_width);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "entry_fullscreen_width", entry_fullscreen_width,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_fullscreen_width);
  gtk_table_attach (GTK_TABLE (table7), entry_fullscreen_width, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_fullscreen_height = gtk_entry_new_with_max_length (4);
  gtk_widget_ref (entry_fullscreen_height);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "entry_fullscreen_height", entry_fullscreen_height,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_fullscreen_height);
  gtk_table_attach (GTK_TABLE (table7), entry_fullscreen_height, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton_window_size_adj = gtk_adjustment_new (1, 1, 4, 1, 10, 10);
  spinbutton_window_size = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_window_size_adj), 1, 0);
  gtk_widget_ref (spinbutton_window_size);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "spinbutton_window_size", spinbutton_window_size,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton_window_size);
  gtk_table_attach (GTK_TABLE (table7), spinbutton_window_size, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label27 = gtk_label_new ("Miscelaneous");
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label27);

  table3 = gtk_table_new (2, 3, FALSE);
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (notebook1), table3);

  entry_cd_system_filename = gtk_entry_new ();
  gtk_widget_ref (entry_cd_system_filename);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "entry_cd_system_filename", entry_cd_system_filename,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_cd_system_filename);
  gtk_table_attach (GTK_TABLE (table3), entry_cd_system_filename, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_browse_cd_system = gtk_button_new_with_label ("Browse ...");
  gtk_widget_ref (button_browse_cd_system);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "button_browse_cd_system", button_browse_cd_system,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_browse_cd_system);
  gtk_table_attach (GTK_TABLE (table3), button_browse_cd_system, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);

  label20 = gtk_label_new ("Default rom directory : ");
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table3), label20, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_SHRINK), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label19 = gtk_label_new ("CD system filename : ");
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table3), label19, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_SHRINK), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  entry_rom_basedir = gtk_entry_new ();
  gtk_widget_ref (entry_rom_basedir);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "entry_rom_basedir", entry_rom_basedir,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_rom_basedir);
  gtk_table_attach (GTK_TABLE (table3), entry_rom_basedir, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_editable (GTK_ENTRY (entry_rom_basedir), FALSE);

  button_browse_rom_dirname = gtk_button_new_with_label ("Browse ...");
  gtk_widget_ref (button_browse_rom_dirname);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "button_browse_rom_dirname", button_browse_rom_dirname,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_browse_rom_dirname);
  gtk_table_attach (GTK_TABLE (table3), button_browse_rom_dirname, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);

  label_paths = gtk_label_new ("Paths");
  gtk_widget_ref (label_paths);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label_paths", label_paths,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_paths);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label_paths);

  table4 = gtk_table_new (2, 3, FALSE);
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (notebook1), table4);

  checkbutton_minimal_bios = gtk_check_button_new_with_label ("Soft bios emulation mode");
  gtk_widget_ref (checkbutton_minimal_bios);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "checkbutton_minimal_bios", checkbutton_minimal_bios,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton_minimal_bios);
  gtk_table_attach (GTK_TABLE (table4), checkbutton_minimal_bios, 0, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label21 = gtk_label_new ("CD path : ");
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table4), label21, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  entry_cd_path = gtk_entry_new ();
  gtk_widget_ref (entry_cd_path);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "entry_cd_path", entry_cd_path,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_cd_path);
  gtk_table_attach (GTK_TABLE (table4), entry_cd_path, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_browse_cd_path = gtk_button_new_with_label ("Browse ...");
  gtk_widget_ref (button_browse_cd_path);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "button_browse_cd_path", button_browse_cd_path,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_browse_cd_path);
  gtk_table_attach (GTK_TABLE (table4), button_browse_cd_path, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);

  label_cd = gtk_label_new ("Cd emulation");
  gtk_widget_ref (label_cd);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label_cd", label_cd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_cd);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label_cd);

  table5 = gtk_table_new (3, 2, FALSE);
  gtk_widget_ref (table5);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "table5", table5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (notebook1), table5);

  label22 = gtk_label_new ("Output frequency : ");
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table5), label22, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label22), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  entry_output_frequency = gtk_entry_new_with_max_length (5);
  gtk_widget_ref (entry_output_frequency);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "entry_output_frequency", entry_output_frequency,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_output_frequency);
  gtk_table_attach (GTK_TABLE (table5), entry_output_frequency, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_buffer_size = gtk_entry_new ();
  gtk_widget_ref (entry_buffer_size);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "entry_buffer_size", entry_buffer_size,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_buffer_size);
  gtk_table_attach (GTK_TABLE (table5), entry_buffer_size, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label23 = gtk_label_new ("Buffer size : ");
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table5), label23, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  checkbutton_stereo_sound = gtk_check_button_new_with_label ("Use stereo sound");
  gtk_widget_ref (checkbutton_stereo_sound);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "checkbutton_stereo_sound", checkbutton_stereo_sound,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton_stereo_sound);
  gtk_table_attach (GTK_TABLE (table5), checkbutton_stereo_sound, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label_sound = gtk_label_new ("Sound");
  gtk_widget_ref (label_sound);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "label_sound", label_sound,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_sound);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label_sound);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox1, FALSE, TRUE, 0);

  buttongeneral_config_close = gtk_button_new_with_label ("OK");
  gtk_widget_ref (buttongeneral_config_close);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "buttongeneral_config_close", buttongeneral_config_close,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (buttongeneral_config_close);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), buttongeneral_config_close);
  GTK_WIDGET_SET_FLAGS (buttongeneral_config_close, GTK_CAN_DEFAULT);

  button_general_config_save = gtk_button_new_with_label ("Save");
  gtk_widget_ref (button_general_config_save);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "button_general_config_save", button_general_config_save,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_general_config_save);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_general_config_save);
  GTK_WIDGET_SET_FLAGS (button_general_config_save, GTK_CAN_DEFAULT);

  button_general_config_cancel = gtk_button_new_with_label ("Cancel");
  gtk_widget_ref (button_general_config_cancel);
  gtk_object_set_data_full (GTK_OBJECT (general_settings_window), "button_general_config_cancel", button_general_config_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_general_config_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_general_config_cancel);
  GTK_WIDGET_SET_FLAGS (button_general_config_cancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (general_settings_window), "show",
                      GTK_SIGNAL_FUNC (on_general_settings_window_show),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_browse_cd_system), "clicked",
                      GTK_SIGNAL_FUNC (on_button_browse_cd_system_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_browse_rom_dirname), "clicked",
                      GTK_SIGNAL_FUNC (on_button_browse_rom_dirname_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_browse_cd_path), "clicked",
                      GTK_SIGNAL_FUNC (on_button_browse_cd_path_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (buttongeneral_config_close), "clicked",
                      GTK_SIGNAL_FUNC (on_buttongeneral_config_close_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_general_config_save), "clicked",
                      GTK_SIGNAL_FUNC (on_button_general_config_save_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_general_config_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_button_general_config_cancel_clicked),
                      NULL);

  return general_settings_window;
}

GtkWidget*
create_window_about (void)
{
  GtkWidget *window_about;
  GtkWidget *table6;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *alignment4;
  GtkWidget *button_close_about;

  window_about = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_about), "window_about", window_about);
  gtk_window_set_title (GTK_WINDOW (window_about), "About Hu-Go!");
  gtk_window_set_position (GTK_WINDOW (window_about), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (window_about), TRUE, TRUE, TRUE);

  table6 = gtk_table_new (4, 1, FALSE);
  gtk_widget_ref (table6);
  gtk_object_set_data_full (GTK_OBJECT (window_about), "table6", table6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table6);
  gtk_container_add (GTK_CONTAINER (window_about), table6);

  label24 = gtk_label_new ("HU-GO!");
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (window_about), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table6), label24, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label24), 10, 10);

  label25 = gtk_label_new ("Multi platform Pc engine emulator");
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (window_about), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table6), label25, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label25), TRUE);

  label26 = gtk_label_new ("Maintainer : Zeograd\nHomepage : http://www.zeograd.com\nIRC : #utopiasoft @ Efnet\nThis software wouldn't have been here without the help of :\nDavid Shadoff\nBt Garner\nNyef\nMooz\nCleaner\nBero\nHmmx\nVideoman\nEagan\nGravis Zero\nRaph99\nFagemul\nIxion\nLester Barrow\nAnd many others I can't cite here but I don't forget");
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (window_about), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table6), label26, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_ref (alignment4);
  gtk_object_set_data_full (GTK_OBJECT (window_about), "alignment4", alignment4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (alignment4);
  gtk_table_attach (GTK_TABLE (table6), alignment4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button_close_about = gtk_button_new_with_label ("Close");
  gtk_widget_ref (button_close_about);
  gtk_object_set_data_full (GTK_OBJECT (window_about), "button_close_about", button_close_about,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_close_about);
  gtk_container_add (GTK_CONTAINER (alignment4), button_close_about);

  gtk_signal_connect (GTK_OBJECT (button_close_about), "clicked",
                      GTK_SIGNAL_FUNC (on_button_close_about_clicked),
                      NULL);

  return window_about;
}

GtkWidget*
create_fileselection_cd_system (void)
{
  GtkWidget *fileselection_cd_system;
  GtkWidget *ok_button_cd_system;
  GtkWidget *cancel_button_cd_system;

  fileselection_cd_system = gtk_file_selection_new ("Select CD System rom");
  gtk_object_set_data (GTK_OBJECT (fileselection_cd_system), "fileselection_cd_system", fileselection_cd_system);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_cd_system), 10);

  ok_button_cd_system = GTK_FILE_SELECTION (fileselection_cd_system)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_cd_system), "ok_button_cd_system", ok_button_cd_system);
  gtk_widget_show (ok_button_cd_system);
  GTK_WIDGET_SET_FLAGS (ok_button_cd_system, GTK_CAN_DEFAULT);

  cancel_button_cd_system = GTK_FILE_SELECTION (fileselection_cd_system)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_cd_system), "cancel_button_cd_system", cancel_button_cd_system);
  gtk_widget_show (cancel_button_cd_system);
  GTK_WIDGET_SET_FLAGS (cancel_button_cd_system, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ok_button_cd_system), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button_cd_system_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cancel_button_cd_system), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button_cd_system_clicked),
                      NULL);

  return fileselection_cd_system;
}

GtkWidget*
create_fileselection_cd_path (void)
{
  GtkWidget *fileselection_cd_path;
  GtkWidget *ok_button_cd_path;
  GtkWidget *cancel_button_cd_path;

  fileselection_cd_path = gtk_file_selection_new ("Select device for cdrom");
  gtk_object_set_data (GTK_OBJECT (fileselection_cd_path), "fileselection_cd_path", fileselection_cd_path);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_cd_path), 10);

  ok_button_cd_path = GTK_FILE_SELECTION (fileselection_cd_path)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_cd_path), "ok_button_cd_path", ok_button_cd_path);
  gtk_widget_show (ok_button_cd_path);
  GTK_WIDGET_SET_FLAGS (ok_button_cd_path, GTK_CAN_DEFAULT);

  cancel_button_cd_path = GTK_FILE_SELECTION (fileselection_cd_path)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_cd_path), "cancel_button_cd_path", cancel_button_cd_path);
  gtk_widget_show (cancel_button_cd_path);
  GTK_WIDGET_SET_FLAGS (cancel_button_cd_path, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ok_button_cd_path), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button_cd_path_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cancel_button_cd_path), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button_cd_path_clicked),
                      NULL);

  return fileselection_cd_path;
}

GtkWidget*
create_fileselection_rom_path (void)
{
  GtkWidget *fileselection_rom_path;
  GtkWidget *ok_button_rom_path;
  GtkWidget *cancel_button_rom_path;

  fileselection_rom_path = gtk_file_selection_new ("Select default rom path");
  gtk_object_set_data (GTK_OBJECT (fileselection_rom_path), "fileselection_rom_path", fileselection_rom_path);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_rom_path), 10);

  ok_button_rom_path = GTK_FILE_SELECTION (fileselection_rom_path)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_rom_path), "ok_button_rom_path", ok_button_rom_path);
  gtk_widget_show (ok_button_rom_path);
  GTK_WIDGET_SET_FLAGS (ok_button_rom_path, GTK_CAN_DEFAULT);

  cancel_button_rom_path = GTK_FILE_SELECTION (fileselection_rom_path)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_rom_path), "cancel_button_rom_path", cancel_button_rom_path);
  gtk_widget_show (cancel_button_rom_path);
  GTK_WIDGET_SET_FLAGS (cancel_button_rom_path, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ok_button_rom_path), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button_rom_path_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cancel_button_rom_path), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button_rom_path_clicked),
                      NULL);

  return fileselection_rom_path;
}

GtkWidget*
create_window_manual (void)
{
  GtkWidget *window_manual;
  GtkWidget *vbox4;
  GtkWidget *scrolledwindow1;
  GtkWidget *text_manual;
  GtkWidget *button_manual_close;

  window_manual = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_manual), "window_manual", window_manual);
  gtk_widget_set_usize (window_manual, 550, 300);
  gtk_window_set_title (GTK_WINDOW (window_manual), "Hu-Go! manual");

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (window_manual), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (window_manual), vbox4);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (window_manual), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  text_manual = gtk_text_new (NULL, NULL);
  gtk_widget_ref (text_manual);
  gtk_object_set_data_full (GTK_OBJECT (window_manual), "text_manual", text_manual,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text_manual);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), text_manual);

  button_manual_close = gtk_button_new_with_label ("Close");
  gtk_widget_ref (button_manual_close);
  gtk_object_set_data_full (GTK_OBJECT (window_manual), "button_manual_close", button_manual_close,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_manual_close);
  gtk_box_pack_end (GTK_BOX (vbox4), button_manual_close, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (button_manual_close), "clicked",
                      GTK_SIGNAL_FUNC (on_button_manual_close_clicked),
                      NULL);

  return window_manual;
}

