.TH hugo_server "1"
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
hugo_server \- server for multiplay
.SH SYNOPSIS
.B hugo_server
.I "[options] ..."
.SH "DESCRIPTION"
This manual page documents briefly the
.BR hugo_server command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, it has documentation in the GNU Info format; see below.
.br
This man should be completed before any release
.PP
.B hugo_server
is a program that run a server for connecting multiple hugo clients
.SH AUTHOR
This manual page was written by Olivier Jolly <olivier.jolly@pcedev.com>,
for the Debian GNU/Linux system (but may be used by others).
